server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: infraestructure-apigateway
  cloud:
    gateway:
      routes:

      - id: keycloak_service
        uri: lb://infraestructure-keycloak
        predicates:
        - Path=/api/security/**
